### ISSUE TITLE
Přidat další parametr u zadávání přednášek: "Odbornost".

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#16]
Ideálně i s info popup otazníkem, s kratkým vysvětlím.
Range: 1-3 (3 neobtížnější)

**Comment by JanMlcoch** [comment]
Za mě ideální 3 možnosti: "Laik", "Normální" a "Odborná" s tím že bude předvybraná možnost "Normální" a všechny stávající přednášky dostanou "Normální"

**Comment by mostja01** [comment]
A odbornost zobrazovat už v preview nebo až po rozkliknutí přednášky?

**Comment by JanMlcoch** [comment]
Navrhuju tam udělat nějakou ikonku už v preview. Ta ikonka bude mít title kde se zobrazí text s odborností

**Comment by Kappyba** [comment]
Pokud se vymyslí nějaká ikonka, tak by to bylo fajn, každopádně klidně bych to nechal až po rozkliknutí.

**Comment by mostja01** [comment]
A co na preview ikony takhle 
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/56202269/202903670-986a6c38-b9d1-473d-982a-8efee700397a.png">
Kde book = laik, school = Normální a starts = Odborník?

**Comment by mostja01** [comment]
A v detailu takhle? 
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/56202269/202904514-e300844c-b415-4bb7-806d-afda6179a516.png">
Ale mám konflikt s tou school ikonou

**Comment by JanMlcoch** [comment]
Za mě super
