### ISSUE TITLE
Odebrat sekci "Nedávno přidané" v talks a graficky označit neviděné/nové v ostatních.

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#43]
Hodit menší tag vlevo nahoru "nové", ať už nové za posledních x dnů, nebo dosud neviděné.

**Comment by mostja01** [comment]
Měli bychom u uživatele uchovávat timestamp poslední návštěvy stránky "Přednášky"? A poté na základě porovnání aktuální návštěvy přidat tento tag?

**Comment by mostja01** [comment]
A seřadit to primárně od nejnovějších nebo podle počtu hlasů, pokud už nebude nedávno přidané?

**Comment by mostja01** [comment]
Mohlo by to vypadat takhle? 
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/56202269/204097965-1807ca19-597e-4dd7-9d50-751a1880ef8f.png">

**Comment by Kappyba** [comment]
Takhle by to bylo svkělé, možná text akorát změnit na "Nové". 

Nechat řazení primárně podle hlasů, akorát tam přidat tag.

A otázka jak moc se ti s tím chce dělat. Nevím na čem funguje tahle varianta. Pokud se ti chce dělat s timestampem, tak klidně, ale úplně stejně dobře bude za mě fungovat timestamp přidání přednášky, který už teď je. Akorát to udělat jako tag.

**Comment by mostja01** [comment]
tahle varianta zatí funguje pouze na tom, že jsou dané přednášky mladší 7 dní od přidání. Pokud by mělo být zobrazováno "Nové" na každé ještě neviděné, pak vidím jediný způsob jako uchovávat timestamp poslední návštěvy daného uživatele pro danou stránku

**Comment by mostja01** [comment]
Je tam jen reusnutý label pro hlasy a alignovaný doleva

**Comment by mostja01** [comment]
Bylo by i možné zachovat barvu, nicméně takhle mi to přijde více kontrastní

**Comment by Kappyba** [comment]
Takhle to úplně stačí :) možná bych snížil čas na 5 dní, resp. Postupně před akcí snižoval
