### ISSUE TITLE
Přidat partnera Brnoc

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#47]
https://brnoc.cz/

**Comment by mostja01** [comment]
Máme aktuální logo? Nebo použít uvodní logo na jejich stránkách?

**Comment by Kappyba** [comment]
Seženu vektor, bohužel to čeká na naše logo ve vektoru :/

**Comment by mostja01** [comment]
Takže použít tohle oko?

**Comment by Kappyba** [comment]
Ano
