### ISSUE TITLE
Opravit šířku uvodni stranky a profilu na mobilu 

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#54]
![Screenshot_20221127-113414_Brave](https://user-images.githubusercontent.com/118224849/204130858-1812ecdd-a437-4b2c-9992-00c96423419d.jpg)
![Screenshot_20221127-113642_Brave](https://user-images.githubusercontent.com/118224849/204130862-39009f34-d9bc-430c-8877-4b7b98a71b1c.jpg)

**Comment by mostja01** [comment]
Prosím @Kappyba , zkontrolovat, ale IMO not valid

**Comment by Kappyba** [comment]
Asi vyřešeno jiným fixem. Zavírám.
