### ISSUE TITLE
Stranka FAQ na mobilu má useknutý konec

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#55]
![Screenshot_20221127-135019_Brave](https://user-images.githubusercontent.com/118224849/204136195-1eb85374-ca8d-43c9-b74e-40bfe14f0b55.jpg)
Při scrollování dolů stránka konci zároveň s boxem FAQ. Prodloužit to, ať to není useklé a ať je tam trochu bílé.

**Comment by mostja01** [comment]
Nejenom u mobilů
