### ISSUE TITLE
Tick box na konci stránky + přednášky řazeny pod sebou, míst vedle sebe v profilu

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#59]
https://i.imgur.com/AYTfkH1.png
https://i.imgur.com/4NtTkUK.png

**Comment by mostja01** [comment]
Tady jsme se asi nepochopili s těma přednáškama... Dělal jsem to tak schválně... Nicméně to fixnu

**Comment by Kappyba** [comment]
No jde o to, že na mobilu tl sice vypadá dobře, ale na noťasu máš obrovskou obrazovku na šířku ale přednášky ti jdou pod sebou s obrovským prázdným místem.

**Comment by Kappyba** [comment]
Obecně se mi nelíbí, že je většina stránky nevyužitá. Graficky to není moc dobré. Viz #30

**Comment by mostja01** [comment]
Pro širší monitory:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/56202269/205488099-4ca0e794-d3e4-40f2-afcf-c9d90e400f39.png">

Pro mobily:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/56202269/205488145-5f31b178-cb4c-4753-a07a-2aeb6f939215.png">
