### ISSUE TITLE
Všechna tlačítka by měla být široká přes celou obrazovku (mobile)

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#60]
Sign up, sign in, přidat přednášku, přihlásit/registrace v drop down menu.

**Comment by mostja01** [comment]
Je přihlásit se/registrace něco jiného než sign-in/sign-up? Jen pro jistotu...

**Comment by Kappyba** [comment]
![image](https://user-images.githubusercontent.com/118224849/209933885-c12870d3-4758-46cd-a111-f4944d1a83aa.png)
Měl jsem na mysli toto, ale popravdě teď nevím jestli to je rozumné... každopádně to celé menu vypadá divně a to hlavně na mobilu. Přišlo by mi logické aby mobilní tlačítka byly přes celou obrazovku, ale chtělo by to rework celého designu těch stránek.

**Comment by Kappyba** [comment]
Při udělání problému #66 to bude vypadat dobře, jen musí být zbytek textu vycentrovaný na mobilu. 

Takže... v Menu v mobilní verzi udělat tlačítka "přihlásit" a "registrace" přes celou šířku stránky.
To stejné udělat v "Přednášky" a profilu s tlačítkem "přidat přednášku".
V .../sign-in tlačítko "Přihlásit"
V .../sign-up tlačítko "Registrovat se na akci"
v "o akci" tlačítka "Ukázat na mapě", "program přednášek" a "Registrace"
