### ISSUE TITLE
Tlačítko "odhlásit" v drop down menu by melo byt stejné jako ostatní tlačítka a ne underline.

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#61]

**Comment by mostja01** [comment]
Tady jen to tlačítko odhlásit nebo také uživatel?

**Comment by Kappyba** [comment]
Asi by nebylo od věci mít obě jako tlačítka a ne odkazy, ale nemůžou vypadat stejně, protože by to nevypadalo dobře podle mě. Takže určitě předělat odhlásit a zkusit nějaký blbosti s tím jménem.

**Comment by Kappyba** [comment]
Prozatím aspoň udělat odhlásit jako tlačítko a ne odkaz prosím. s uživatelem si potom ještě pohrajeme.
