### ISSUE TITLE
Přednášky v talks nejsou na mobilu vycentrované

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#63]
![Screenshot_20221201-092131_Brave](https://user-images.githubusercontent.com/118224849/205002161-b50bdbc1-1e5a-4364-9493-bb96255b3d1d.jpg)
Vlevo je větší mezera než vpravo. Klidně bych nechal tu levou, ale nedokážu si to moc představit. 

Edit: dal bych něco mezi (tak jak v profilu, viz níže)

**Comment by Kappyba** [comment]
V profilu je to už ok 
![Screenshot_20221201-092142_Brave](https://user-images.githubusercontent.com/118224849/205002387-562f1595-1f88-42dd-9c93-265956b47ecf.jpg)

**Comment by mostja01** [comment]
div.container in talks.component.html

**Comment by mostja01** [comment]
Prosím, zkontrolovat, ale IMO not valid

**Comment by Kappyba** [comment]
Nevím přesně co tím myslíš. Každopádně momentální stav je, že na mobilu v profilu mají přednášky na obou stranách stejný offset, zatímco v "přednáškách" mají na levo větší offset než na pravo, viz prvotní obrázek.

**Comment by mostja01** [comment]
No já to vidím se stejným okrajem i v přednáškách...
<img width="444" alt="image" src="https://user-images.githubusercontent.com/56202269/211651433-f01a82a3-8840-40c6-b85d-81372d72c439.png">

**Comment by mostja01** [comment]
Ok, zdá se být u hodně úzkých zařízení (menší než 390px)
