### ISSUE TITLE
Upravit drop-down menu na mobilu.

### ISSUE THREAD

**Issue by Kappyba** [JanMlcoch/prednaskovy-maraton#66]
Graficky to vypadá jak z roku 2010 - nic ve zlém. Asi nejvíc mě tam bije do očí #62, #61 ale hlavně tohle tlačítko: 
![image](https://user-images.githubusercontent.com/118224849/205116679-da17fa0f-4203-4676-ba33-a905186da909.png)

**Comment by Kappyba** [comment]
Jo... a taky posunout prosím to logo tak, aby bylo zarovnané s textem, ale možná mě klame jen to tlačítko.

**Comment by mostja01** [comment]
A co se tady navrhuje místo toho? :-)

**Comment by Kappyba** [comment]
Udělal bych to po vzoru https://brnoc.cz/
![image](https://user-images.githubusercontent.com/118224849/211200113-602b7522-f0da-48df-83d7-47516db523e4.png)
![image](https://user-images.githubusercontent.com/118224849/211200127-981cb5e6-408e-4455-b9ce-d24b5c23c366.png)


Mít logo viditelné po celou dobu a ne jenom až po otevření menu a nechat ho v jednom rohu (nevím která varianta bude vypadat lépe jestli logo v pravém a menu v levém nebo naopak - prosím odzkoušení obou, pokud možno). a po rozkliknutí menu zvýraznit ten čtvereč okolo nebo nevím jak nazvat - jen ať to nevypadá jak tlačítko.

**Comment by Kappyba** [comment]
+ udělat výraznější text těch textových polích v menu - větší písmo, bold, jiný font, nevím...
